language: python

python:
  - "2.7"
  - "3.6"

cache:
  - apt
  - pip

addons:
  apt:
    packages:
    - python-dev

before_install:
  - "travis_retry pip install --upgrade pip"

install:
  - "travis_retry pip install --upgrade -r requirements.txt"

script:
  - python setup.py install
  - pytest testsuite

after_success:
  - coveralls

sudo: false

deploy:
  skip_existing: true
  provider: pypi
  user: "__token__"
  password:
    secure: Ijn+smkI60E+9Q2XRwQVHvOwdTeIY44HWUlKzdQHCTWXy2caMYQ03jNcdVz12wBGTAV4QwlygkMl1NDVjol+Yo3M/s/Ak6ujhQYAEXmm5Zwg8upb4m+3zXzQYvH6jpxWSjCkR/4ZBWeJuKGUrzc7AupEXxmUQKY/FONsieoGfmHRzwCLKtLMfccS7Qva/3adif29tRXitX/HblJj/mjooge7Cqfnoi+C8VA8RoWIxjnGQkdd+ZsFjc9C2e+qpnfgZLULyJIkMuyMKk550JxfkR/fuJllFjBBHLn0WGf1ERX7e/YfAOf00kst17PvF1hx3Pt5cpRQE3LOZTJjdIWRymlV9GQCx4iX+/K9QHFihxs+nfzQVkKaaalZyO8gDJPem9zoFRKEDHRUFHoDiikefAS33BdM44TUXxCcc1hX6M6kZ9qJJj5pYoAnJqv0iE+ZAniJbL3sVb5jIg8zmGE9qMGis1rEWIyFVcvoGRaM9JJfw3GbjIiVL91PctQJXkkpjOr+aI84uTmbKcHXf2DHcIRMjqnkaMdN4UCIL4MFXRp4aKZTaLBc8Y8LDLRNiCHEzip8E9I3Shsxan/0RPUXVOA7zpIixj6ms2MXNzrQpCZ60XP61sXAT60eRsKu9yfib/+rt+ZpOVo4aB8Oaxbct4Txp9ve4N7pw46l4w/a1yk=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    repo: HEPData/hepdata-validator